// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Knowledge_Systems.Server.Data;

#nullable disable

namespace School_Knowledge_Systems_SKS.Server.Migrations
{
    [DbContext(typeof(SKSDbContext))]
    partial class SKSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Level", b =>
                {
                    b.Property<string>("LevelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.HasKey("LevelID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NoOfClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("SectionID");

                    b.HasIndex("LevelID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.SectionSubject", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectID", "SectionID");

                    b.HasIndex("SectionID");

                    b.ToTable("SectionSubjects");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Student", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FatherPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SectionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("SectionID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("SubjectID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectID = "Default Subject",
                            LevelID = "1",
                            NoOfClassesPerWeek = 3,
                            TeacherID = 1
                        });
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeacherClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            PhoneNumber = 1234567890,
                            TeacherClassesPerWeek = 5,
                            TeacherName = "Default Teacher"
                        });
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Level", "Level")
                        .WithMany("Sections")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.SectionSubject", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Section", "Section")
                        .WithMany("Subjects")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Knowledge_Systems.Server.Models.Subject", "Subject")
                        .WithMany("Sections")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Student", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Teacher", "Teacher")
                        .WithMany("TaughtSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Level", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Teacher", b =>
                {
                    b.Navigation("TaughtSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
